# These are supported funding model platforms

github: [HarryUnchained]
# open_collective: machine-gun
# ko_fi: harryunchained
# buy_me_a_coffee: harryunchained
# custom: ['https://paypal.me/yourname']
